spring:
  application:
    name: flex-analytics
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:123456}
server:
  port: ${SERVER_PORT:8081}

app:
  cli:
    enabled: ${CLI_ENABLED:false}
  input-file: ${INPUT_FILE:classpath:analytics.csv}
  output-file: ${OUTPUT_FILE:output/analytics_output.csv}
  correlation-method: PEARSON

logging:
  level:
    root: INFO
  file:
    name: ${LOG_FILE:logs/app.log}
