spring:
  application:
    name: flex-analytics
  security:
    user:
      name: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
server:
  port: 8081

app:
  cli:
    enabled: ${CLI_ENABLED:false}
  input-file: ${INPUT_FILE}
  output-file: ${OUTPUT_FILE}
  correlation-method: ${CORRELATION_METHOD:PEARSON}
  max-file-size: 10MB

logging:
  level:
    root: INFO
  file:
    name: ${LOG_FILE}
